// AUTO-GENERATED by scripts/build-country-regions.mjs — do not edit by hand.
// Natural Earth 110m admin-0 countries (public domain), simplified ~0.05°.
// Used ONLY by the quiz editor + MCP to author map_pin region questions.
import type { GeoRegion } from "@/lib/question-registry";

// Single-entry module (Kenya) so the Training demo can import the region
// without pulling the whole dataset into the client bundle.
export const KENYA_REGION: GeoRegion = {
  type: "Polygon",
  coordinates: [[[39.202,-4.677],[37.767,-3.677],[37.699,-3.097],[33.904,-0.95],[33.894,0.11],[34.672,1.177],[35.036,1.906],[34.479,3.556],[34.005,4.25],[35.298,5.506],[35.817,5.338],[35.817,4.777],[36.159,4.448],[36.855,4.448],[38.121,3.599],[38.671,3.616],[38.893,3.501],[39.559,3.422],[39.855,3.839],[40.768,4.257],[41.172,3.919],[41.855,3.919],[40.981,2.785],[40.993,-0.858],[41.585,-1.683],[40.885,-2.083],[40.638,-2.5],[40.263,-2.573],[40.121,-3.278],[39.8,-3.681],[39.605,-4.347],[39.202,-4.677]]],
};

export const KENYA_LABEL = { lat: 0.947, lng: 38.237 };
