/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RequestHostingRouteImport } from './routes/request-hosting'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaguesRouteImport } from './routes/leagues'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaguesIndexRouteImport } from './routes/leagues.index'
import { Route as ArenaIndexRouteImport } from './routes/arena.index'
import { Route as QuizzesIdRouteImport } from './routes/quizzes.$id'
import { Route as PlaySessionIdRouteImport } from './routes/play.$sessionId'
import { Route as LeaguesIdRouteImport } from './routes/leagues.$id'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as HostSessionIdRouteImport } from './routes/host.$sessionId'
import { Route as DebugMapRouteImport } from './routes/debug.map'
import { Route as ArenaQuizIdRouteImport } from './routes/arena.$quizId'
import { Route as ArenaQuizIdIndexRouteImport } from './routes/arena.$quizId.index'
import { Route as ArenaQuizIdPlayRouteImport } from './routes/arena.$quizId.play'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestHostingRoute = RequestHostingRouteImport.update({
  id: '/request-hosting',
  path: '/request-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesRoute = LeaguesRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaguesRoute,
} as any)
const ArenaIndexRoute = ArenaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArenaRoute,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySessionIdRoute = PlaySessionIdRouteImport.update({
  id: '/play/$sessionId',
  path: '/play/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIdRoute = LeaguesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeaguesRoute,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSessionIdRoute = HostSessionIdRouteImport.update({
  id: '/host/$sessionId',
  path: '/host/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugMapRoute = DebugMapRouteImport.update({
  id: '/debug/map',
  path: '/debug/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaQuizIdRoute = ArenaQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaQuizIdIndexRoute = ArenaQuizIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArenaQuizIdRoute,
} as any)
const ArenaQuizIdPlayRoute = ArenaQuizIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => ArenaQuizIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRouteWithChildren
  '/auth': typeof AuthRoute
  '/branding': typeof BrandingRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/request-hosting': typeof RequestHostingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/arena/$quizId': typeof ArenaQuizIdRouteWithChildren
  '/debug/map': typeof DebugMapRoute
  '/host/$sessionId': typeof HostSessionIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$id': typeof LeaguesIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/arena/': typeof ArenaIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/arena/$quizId/play': typeof ArenaQuizIdPlayRoute
  '/arena/$quizId/': typeof ArenaQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/branding': typeof BrandingRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/request-hosting': typeof RequestHostingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/debug/map': typeof DebugMapRoute
  '/host/$sessionId': typeof HostSessionIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$id': typeof LeaguesIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/arena': typeof ArenaIndexRoute
  '/leagues': typeof LeaguesIndexRoute
  '/arena/$quizId/play': typeof ArenaQuizIdPlayRoute
  '/arena/$quizId': typeof ArenaQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena': typeof ArenaRouteWithChildren
  '/auth': typeof AuthRoute
  '/branding': typeof BrandingRoute
  '/competitions': typeof CompetitionsRoute
  '/dashboard': typeof DashboardRoute
  '/leagues': typeof LeaguesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/request-hosting': typeof RequestHostingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/arena/$quizId': typeof ArenaQuizIdRouteWithChildren
  '/debug/map': typeof DebugMapRoute
  '/host/$sessionId': typeof HostSessionIdRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$id': typeof LeaguesIdRoute
  '/play/$sessionId': typeof PlaySessionIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/arena/': typeof ArenaIndexRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/arena/$quizId/play': typeof ArenaQuizIdPlayRoute
  '/arena/$quizId/': typeof ArenaQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/branding'
    | '/competitions'
    | '/dashboard'
    | '/leagues'
    | '/profile'
    | '/request-hosting'
    | '/sitemap.xml'
    | '/training'
    | '/arena/$quizId'
    | '/debug/map'
    | '/host/$sessionId'
    | '/join/$code'
    | '/leagues/$id'
    | '/play/$sessionId'
    | '/quizzes/$id'
    | '/arena/'
    | '/leagues/'
    | '/arena/$quizId/play'
    | '/arena/$quizId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/branding'
    | '/competitions'
    | '/dashboard'
    | '/profile'
    | '/request-hosting'
    | '/sitemap.xml'
    | '/training'
    | '/debug/map'
    | '/host/$sessionId'
    | '/join/$code'
    | '/leagues/$id'
    | '/play/$sessionId'
    | '/quizzes/$id'
    | '/arena'
    | '/leagues'
    | '/arena/$quizId/play'
    | '/arena/$quizId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena'
    | '/auth'
    | '/branding'
    | '/competitions'
    | '/dashboard'
    | '/leagues'
    | '/profile'
    | '/request-hosting'
    | '/sitemap.xml'
    | '/training'
    | '/arena/$quizId'
    | '/debug/map'
    | '/host/$sessionId'
    | '/join/$code'
    | '/leagues/$id'
    | '/play/$sessionId'
    | '/quizzes/$id'
    | '/arena/'
    | '/leagues/'
    | '/arena/$quizId/play'
    | '/arena/$quizId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArenaRoute: typeof ArenaRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrandingRoute: typeof BrandingRoute
  CompetitionsRoute: typeof CompetitionsRoute
  DashboardRoute: typeof DashboardRoute
  LeaguesRoute: typeof LeaguesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RequestHostingRoute: typeof RequestHostingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrainingRoute: typeof TrainingRoute
  DebugMapRoute: typeof DebugMapRoute
  HostSessionIdRoute: typeof HostSessionIdRoute
  JoinCodeRoute: typeof JoinCodeRoute
  PlaySessionIdRoute: typeof PlaySessionIdRoute
  QuizzesIdRoute: typeof QuizzesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-hosting': {
      id: '/request-hosting'
      path: '/request-hosting'
      fullPath: '/request-hosting'
      preLoaderRoute: typeof RequestHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof LeaguesRoute
    }
    '/arena/': {
      id: '/arena/'
      path: '/'
      fullPath: '/arena/'
      preLoaderRoute: typeof ArenaIndexRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$sessionId': {
      id: '/play/$sessionId'
      path: '/play/$sessionId'
      fullPath: '/play/$sessionId'
      preLoaderRoute: typeof PlaySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$id': {
      id: '/leagues/$id'
      path: '/$id'
      fullPath: '/leagues/$id'
      preLoaderRoute: typeof LeaguesIdRouteImport
      parentRoute: typeof LeaguesRoute
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$sessionId': {
      id: '/host/$sessionId'
      path: '/host/$sessionId'
      fullPath: '/host/$sessionId'
      preLoaderRoute: typeof HostSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/map': {
      id: '/debug/map'
      path: '/debug/map'
      fullPath: '/debug/map'
      preLoaderRoute: typeof DebugMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/$quizId': {
      id: '/arena/$quizId'
      path: '/$quizId'
      fullPath: '/arena/$quizId'
      preLoaderRoute: typeof ArenaQuizIdRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/$quizId/': {
      id: '/arena/$quizId/'
      path: '/'
      fullPath: '/arena/$quizId/'
      preLoaderRoute: typeof ArenaQuizIdIndexRouteImport
      parentRoute: typeof ArenaQuizIdRoute
    }
    '/arena/$quizId/play': {
      id: '/arena/$quizId/play'
      path: '/play'
      fullPath: '/arena/$quizId/play'
      preLoaderRoute: typeof ArenaQuizIdPlayRouteImport
      parentRoute: typeof ArenaQuizIdRoute
    }
  }
}

interface ArenaQuizIdRouteChildren {
  ArenaQuizIdPlayRoute: typeof ArenaQuizIdPlayRoute
  ArenaQuizIdIndexRoute: typeof ArenaQuizIdIndexRoute
}

const ArenaQuizIdRouteChildren: ArenaQuizIdRouteChildren = {
  ArenaQuizIdPlayRoute: ArenaQuizIdPlayRoute,
  ArenaQuizIdIndexRoute: ArenaQuizIdIndexRoute,
}

const ArenaQuizIdRouteWithChildren = ArenaQuizIdRoute._addFileChildren(
  ArenaQuizIdRouteChildren,
)

interface ArenaRouteChildren {
  ArenaQuizIdRoute: typeof ArenaQuizIdRouteWithChildren
  ArenaIndexRoute: typeof ArenaIndexRoute
}

const ArenaRouteChildren: ArenaRouteChildren = {
  ArenaQuizIdRoute: ArenaQuizIdRouteWithChildren,
  ArenaIndexRoute: ArenaIndexRoute,
}

const ArenaRouteWithChildren = ArenaRoute._addFileChildren(ArenaRouteChildren)

interface LeaguesRouteChildren {
  LeaguesIdRoute: typeof LeaguesIdRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
}

const LeaguesRouteChildren: LeaguesRouteChildren = {
  LeaguesIdRoute: LeaguesIdRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
}

const LeaguesRouteWithChildren =
  LeaguesRoute._addFileChildren(LeaguesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArenaRoute: ArenaRouteWithChildren,
  AuthRoute: AuthRoute,
  BrandingRoute: BrandingRoute,
  CompetitionsRoute: CompetitionsRoute,
  DashboardRoute: DashboardRoute,
  LeaguesRoute: LeaguesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RequestHostingRoute: RequestHostingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrainingRoute: TrainingRoute,
  DebugMapRoute: DebugMapRoute,
  HostSessionIdRoute: HostSessionIdRoute,
  JoinCodeRoute: JoinCodeRoute,
  PlaySessionIdRoute: PlaySessionIdRoute,
  QuizzesIdRoute: QuizzesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
